---
title: "Proposal"
date: "11/4/2019"
output: github_document
---

# Team Registation and Proposal


## The group members (names and UNIs)

* Clayton Snyder (cs3779)
* Keyanna Davis (kd2640)
* Olya Besedina (ob2305)
* Matthew Parker (mp3745)
* Lauren Franks (lf2147)

## The tentative project title 



## The motivation for this project

Stop and Frisk has been a controversial police tactic used for years as a way to briefly stop and search civilians who are of suspect. Police must have "reasonable suspicion" according to the fourth amendment to legally stop a person. Utilizing NYC Stop and Frisk data, we want to give insight into the most influential factors of those who are targeted by the Stop and Frisk tactic.

## The intended final products

Our final products will include a report summarizing our final results, and our entire analytical process of the 2016 Stop & Frisk Data Set, as well as a complimentary website that will provide access and curate the final report; creating visualizations and interactional displays to help guide readers through our report's findings. 

## The anticipated data sources

Our anticipated data source is going to be the publicly available data from NYC/the NYPD located at this URL: [https://www1.nyc.gov/site/nypd/stats/reports-analysis/stopfrisk.page]

We intend on using the data set published from 2016 since the only complete data dictionary we could locate is from the 2016 data set.

If we should need any additional data (like neighborhood demographics, etc.), we will most likely get them from NYC's public database (https://opendata.cityofnewyork.us/).

## The planned analyses / visualizations / coding challenges

#### Analysis

* Where do stops happen in NYC?
  + Visual: Map of stops in NYC using xy coordinates in data
* Are there trends in stops across time (over a year or by hour of day)?
  + Visual: Line plot of stops over time
* Regression analysis to identify key factors to predict if someone who was stopped will then be frisked
  + Visual: ROC curve
* Compare listed reasons that individuals were stopped
  + Visual: Bar chart
  
#### Coding challenges

* With over 12,000 rows and 112 columns, wrangling this dataset may be tricky
* Check data quality and inconsistencies
* Column names and values are not informative, so they need to be changed
* Missing values will need to be addressed
* Based on the provided data dictionary, it appears that there are issues with the `datestop` column that will need to be fixed before analysis

## The planned timeline

###### Week 1 (Nov. 4th - Nov. 7th):
  * Find data and discuss initial plans for the project
  
###### Week 2 (Nov. 11th - Nov. 15th):
  * Import, clean, and tidy data
  * Explore data
  * Come up with final research questions and ideas for visualizations
  
###### Week 3 (Nov. 18th - Nov. 22nd):
  * Exploratory analysis, visualizations, summaries, and statistical analysis
  
###### Week 4 (Nov. 25th - Nov. 29th):
  * Build website
  * Write report
  
###### Week 5 (Dec. 2nd - Dec. 6th):
  * Finalize analysis, website, and report 
  * Record screencast
